name: Install Wordpress To VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Pull Git File
      run: |
          git clone https://github.com/dhiky/wordpress-installation.git /tmp/wp-install

    - name: Check & Install Dependencies
      run: |
          chmod +x /tmp/wp-install/dependencies.sh
          sh /tmp/wp-install/dependencies.sh

    - name: Install WordPress
      run: |
          chmod +x /tmp/wp-install/install.sh
          sh /tmp/wp-install/install.sh
