name: Install Wordpress To VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Configure SSH
      run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/main.key
          chmod 600 ~/.ssh/main.key
          cat >>~/.ssh/config <<EOF
          Host main
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            Port ${{ secrets.SSH_PORT }}
            IdentityFile ~/.ssh/main.key
            StrictHostKeyChecking no
          EOF
        
    - name: Pull Git File
      run: ssh main 'git clone https://github.com/dhiky/wordpress-installation.git /tmp/wp-install'

    - name: Check & Install Dependencies
      run: ssh main 'chmod +x /tmp/wp-install/dependencies.sh && sh /tmp/wp-install/dependencies.sh'

    - name: Install WordPress
      run: ssh main 'chmod +x /tmp/wp-install/install.sh && sh /tmp/wp-install/install.sh'
