name: Install Wordpress To VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Config SSH
      run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/main.key
          chmod 600 ~/.ssh/main.key
          cat >>~/.ssh/config <<END
          Host main
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_HOST }}
            Port ${{ secrets.SSH_PORT }}
            IdentityFile ~/.ssh/main.key
            StrictHostKeyChecking no
          END
          
      env: 
         ROOT_MYSQL : ${{ secrets.ROOT_PASSWD }}
        
    - name: Pull Git File
      run: ssh main 'git clone https://github.com/dhiky/wordpress-installation.git /tmp/wp-install'
      env: 
         ROOT_MYSQL : ${{ secrets.ROOT_PASSWD }}
         
    - name: Check & Install Dependencies
      run: ssh main 'chmod +x /tmp/wp-install/dependencies.sh && sh /tmp/wp-install/dependencies.sh'
      env: 
         ROOT_MYSQL : ${{ secrets.ROOT_PASSWD }}
         
    - name: Install WordPress
      run: ssh main 'chmod +x /tmp/wp-install/install.sh && sh /tmp/wp-install/install.sh'
      env: 
         ROOT_MYSQL : ${{ secrets.ROOT_PASSWD }}
