name: Install Wordpress To VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Pull Git File
      run: git pull origin main:/tmp/wp-install

    - name: Check & Install Dependencies
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $SSH_PRIVATE_KEY username@103.117.56.37 -p2237 << 'EOF'
          chmod +x /tmp/wp-install/dependencies.sh
          /tmp/wp-install/dependencies.sh
        EOF

    - name: Install WordPress
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $SSH_PRIVATE_KEY username@103.117.56.37 -p2237 << 'EOF'
          chmod +x /tmp/wp-install/install.sh.sh
          /tmp/wp-install/install.sh.sh
        EOF
